name: Build and Test .NET MAUI App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest  # Użycie maszyny wirtualnej macOS

    steps:
    # 1. Checkout repozytorium
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Instalacja .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Ustawienie wersji .NET MAUI (możesz użyć wersji 7.0.x lub 8.0.x)

    # 3. Instalacja wymaganych workloadów .NET MAUI (iOS, MacCatalyst, Android)
    - name: Install .NET MAUI iOS, MacCatalyst, and Android workloads
      run: |
        dotnet workload install maui-ios  # Instalacja workloadu iOS
        dotnet workload install maccatalyst  # Instalacja workloadu MacCatalyst
        dotnet workload install android  # Instalacja workloadu Android

    - name: Install .NET MAUI MacCatalyst workload
      run: |

        dotnet workload install maccatalyst  # Instalacja workloadu MacCatalyst
        dotnet workload install android  # Instalacja workloadu Android

    # 5. Wypisanie wersji Xcode, dotnet i simctl dla diagnostyki
    - name: Diagnostic info
      run: |
        echo "Xcode version:"
        xcodebuild -version
        echo "dotnet version:"
        dotnet --version
        echo "Simulators:"
        xcrun simctl list devices

    # 6. Przywracanie zależności
    - name: Install dependencies
      run: |
        dotnet restore

    # 5. Budowanie aplikacji na iOS
    - name: Build the application for iOS
      run: |
        dotnet build FightClub.csproj -t:Build -f:net7.0-ios

    # 6. Uruchamianie testów jednostkowych
    - name: Run unit tests
      run: |
        dotnet test  # Uruchamianie testów jednostkowych

    # 7. Uruchomienie testów UI na symulatorze iPhone SE (2nd generation)
    - name: Run UI tests on iOS Simulator
      run: |
        dotnet maui test --target ios --device "iPhone SE (2nd generation)"
