name: Build and Test .NET MAUI App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest  # Użycie maszyny wirtualnej macOS

    steps:
    # 1. Checkout repozytorium
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Instalacja .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # Ustawienie wersji .NET MAUI (możesz użyć wersji 7.0.x lub 8.0.x)

    # 3. Instalacja wymaganych workloadów .NET MAUI (iOS, MacCatalyst, Android)
    - name: Install .NET MAUI iOS, MacCatalyst, and Android workloads
      run: |
        dotnet workload install maui-ios  # Instalacja workloadu iOS
        dotnet workload install maccatalyst  # Instalacja workloadu MacCatalyst
        dotnet workload install android  # Instalacja workloadu Android

    # 4. Wypisanie wersji Xcode, dotnet i simctl dla diagnostyki
    - name: Diagnostic info
      run: |
        echo "Xcode version:"
        xcodebuild -version
        echo "dotnet version:"
        dotnet --version
        echo "Simulators:"
        xcrun simctl list devices

    # 5. Przywracanie zależności
    - name: Install dependencies
      run: |
        dotnet restore

    # 6. Budowanie aplikacji na iOS
    - name: Build the application for iOS
      run: |
        dotnet build FightClub.csproj -t:Build -f:net7.0-ios

    # 7. Uruchomienie symulatora iOS (np. iPhone SE)
    - name: Boot iOS simulator
      run: |
        # Uruchomienie symulatora
        xcrun simctl boot "iPhone SE (3rd generation)"  # Włączenie symulatora iPhone SE
        # Daj trochę czasu na uruchomienie symulatora
        sleep 60  # Zwiększenie czasu oczekiwania, jeśli potrzeba

    # 8. Sprawdzenie statusu symulatora przed testami
    - name: Ensure simulator is running
      run: |
        # Sprawdzenie, czy symulator jest uruchomiony
        xcrun simctl list devices
        xcrun simctl bootstatus "iPhone SE (3rd generation)"
